
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 10 20:02:19 CEST 2014
//----------------------------------------------------

package compiler.synanal;

/** CUP generated class containing symbol constants. */
public class PascalTok {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int VAL = 36;
  public static final int LTH = 26;
  public static final int FUNCTION = 45;
  public static final int LBRACKET = 14;
  public static final int CONST = 40;
  public static final int CHAR = 8;
  public static final int SEMIC = 18;
  public static final int INT = 9;
  public static final int ARRAY = 37;
  public static final int FOR = 44;
  public static final int NOT = 30;
  public static final int AND = 20;
  public static final int RECORD = 50;
  public static final int TYPE = 53;
  public static final int NIL = 5;
  public static final int OR = 31;
  public static final int BOOL = 7;
  public static final int COMMA = 11;
  public static final int BEGIN = 39;
  public static final int DIV = 21;
  public static final int GEQ = 23;
  public static final int IF = 46;
  public static final int ASSIGN = 38;
  public static final int DOT = 12;
  public static final int UADD = 34;
  public static final int PTR = 32;
  public static final int OF = 47;
  public static final int DOTS = 13;
  public static final int EOF = 0;
  public static final int RBRACKET = 16;
  public static final int INT_CONST = 4;
  public static final int PROGRAM = 49;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int ADD = 19;
  public static final int LPARENTHESIS = 15;
  public static final int NEQ = 29;
  public static final int GTH = 24;
  public static final int EQU = 22;
  public static final int COLON = 10;
  public static final int ELSE = 42;
  public static final int TO = 52;
  public static final int MEM = 27;
  public static final int WHILE = 55;
  public static final int THEN = 51;
  public static final int RPARENTHESIS = 17;
  public static final int LEQ = 25;
  public static final int END = 43;
  public static final int USUB = 35;
  public static final int BOOL_CONST = 2;
  public static final int SUB = 33;
  public static final int VAR = 54;
  public static final int PROCEDURE = 48;
  public static final int DO = 41;
  public static final int IDENTIFIER = 6;

  /* non terminals */
  static final int name_val = 2;
  static final int list_param = 12;
  static final int expr_value_list = 20;
  static final int expr_type = 19;
  static final int declarations_var = 6;
  static final int expr_type_desc = 21;
  static final int decl_type = 10;
  static final int declarations_type = 7;
  static final int decl_const = 8;
  static final int decl_func = 14;
  static final int seq_stmt = 17;
  static final int program = 0;
  static final int desc_param = 11;
  static final int decl_procedure = 13;
  static final int declarations = 3;
  static final int decl_var = 9;
  static final int declarations_subprg = 4;
  static final int expr_value = 18;
  static final int desc_komponente = 22;
  static final int composed_stmt = 16;
  static final int stmt = 15;
  static final int decl_name = 1;
  static final int declarations_const = 5;
}

